[package]
name = "poop-data"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.3.0"
hematite-nbt = "0.5.2"
serde = "1.0.203"
serde_json = "1.0.120"
ssh2 = "0.9.4"

[lib]
name = "poop_scoreboard"
path = "src/lib.rs"

[[bin]]
name = "nbt-to-csv"
path = "src/main.rs"